version: "3.8"
services:
  server:
    container_name: realtime-chat-server
    build:
      context: ./server
      dockerfile: Dockerfile
    ports:
      - "${PORT}:${PORT}"
    env_file:
      - .env
    environment:
      - PORT=${PORT}
    networks:
      - api-network
      - db-network
    depends_on:
      - database

  database:
    container_name: realtime-chat-database
    image: mongo
    ports:
      - "${DB_PORT}:${DB_PORT}"
    networks:
      - db-network
    volumes:
      - mongo-data:/data/db
    env_file:
      - .env
    environment:
      - DB_PORT=${DB_PORT}

networks:
  api-network:
    driver: bridge
  db-network:
    driver: bridge

volumes:
  mongo-data:
    driver: local
