version: "3.8"
services:
  server:
    container_name: realtime-chat-server
    build:
      context: ./server
      dockerfile: Dockerfile
    ports:
      - "${PORT}:${PORT}"
    env_file:
      - .env
    environment:
      - PORT=${PORT}
      - REDIS_URL=${REDIS_URL}
    networks:
      - api-network
      - db-network
      - redis-network
    depends_on:
      - database
      - cache

  database:
    container_name: realtime-chat-database
    image: mongo
    ports:
      - "${DB_PORT}:${DB_PORT}"
    networks:
      - db-network
    volumes:
      - mongo-data:/data/db
    env_file:
      - .env

  cache:
    container_name: realtime-chat-cache
    image: redis:latest
    restart: always
    command: redis-server --save
    networks:
      - redis-network

networks:
  api-network:
    driver: bridge
  db-network:
    driver: bridge
  redis-network:
    driver: bridge

volumes:
  mongo-data:
    driver: local
